language: java

jdk:
- openjdk11

sudo: false
env:
    global:
        #key for github
        #GITHUB_OAUTH_TOKEN
        - secure: "gY0nP7kxUvTBW/64ZiYNMP8vK+kiQ9xGMJuoZC5BVV2CKn6zKfKIfTwiiYKB9q4SMiemGgfS7TSzQyYESvkmC80MGVVx+vq7eGrYaoIwB7ILM5CJOHb4QtQrd5bvMKI2dyK6+U+R7T/RYddeltWyQOSrxROD8L7ArdpZpaGmw/b2FCeCu9pUi1wOtfdfaSXO1eZrwz2D2FatY13QWGFSGMVEDlC8XDioBn+CwbEqoZIjrXWxcplwBmKzI4p5UaLyTFflxk6WJD8gSlnfoZ1cvsJshUUWv7TGYJv5pDLVV3LyJntXHZtIlaVKOfsj4uOKanCpPDab0EPjUe7q7sRjKG12cYQDnQlmMfGuY8JMiblq6jPekGA2x+FKz9nkBEFlR/pnmTATwlqbQ58dMlUOmdxKxqDYa6FzNVIu8qqCX3DK/vSLFpp0B9B7z4i7TKkZcGoJfl9f3bud3Tw/tsTCT5Ecg+Vw+wxx0EsTXRIlUYFT4CS51PJuU78Jpo+3hWCOvw88GbXuRldTVMOmkGum7DgeDwOKwBLo55mLlQ0APdkuTLZor64CqyToZixrbQYaND978ho/9PCaZjKb5G+LcyQgJtmtfa7jVZXh06szbkY6hnhrIFawDRz5/7ruFgqJIgvxsDj9D0YX8AUdGHn7Bhz80eoajiAbKPg9R/z8qnQ="
        - environment=test
        #sonatype credentials
        #OSSRH_JIRA_USERNAME
        - secure: "gWoGd1hug5j+4E+Tz28ohIFX0LgHagBmHPFryEVT7N24ssrBm4B3Y5Jpu7CerHc53ayjbW5xXjXPUWaux4wh/ZDJHO7qfhN4uqxlaJVaoV/1YQvaIdSy95QxDtYoACGs/WWBvVvRxzk9ancZjxaBM905Cj1i5XnC3V/d4XeTU8q/KUosiLN0/BUAGFLvw4EVrTaIo8PP7DqAVWPHsdhgYaK4pzKBoUooZHdprWdzI20o1I07UjkILNHQ66FkaCqN/VT5Zqqi5stQ8F+G800ZaXY8qfh9JULXnhluS/u93R21okLnRNlebgoXqgTZFX0s9/ltgKiE4MHyMuOQh8zuzR5rzOWwUGPwzorq4eXOJbC2uwZvzQRYrxtEaNSyFN6Tl582XZR7Um0zOD0SfUh1E34T/B+Z2C9majSA1wYu1UhI/Z2npiMxV0b0GtSf8mg9BW/yYUegH/E9eIQ6xJEz4BcO4elTBAJ4mJctJSUPciwpDQdbOJsuD6Y8F9Y7/JnPBnZ8CEZHtXWRsOziht0RcGwCkoN2LNVzjym4JjcXoB6WERmyWx5smPoBqy1sG7nAIrP3UsX58TFMc0NVAJdaYlVJeMK0Pzk1szHmd/fTsbxxcZD6Pstbm5D/5UlvfZdZjfZEiwwjqM9Hd12k8gyaMxwNJBVj5qBaRa6RamjQz5M="
        #OSSRH_JIRA_PASSWORD
        - secure: "B0sinvL6Ik7y56ecFnlrgHMOpV6NN84InWA2/S0APUYdpb8EbNFzKHh69xVISF6gwPjQ2byfgZoqxq6XOcb15QcjuLEdq0WR7aDjwPs9clpm49Du+rswKfYiOfqSeNZz0YnU3qOdTvOxORU9GQNUk/FxEyYGlhPgIEmKwuotVgOG4WDIzeVzl51g/vsfSHZvg7jiBDIjZ7m90eVxKYOryudAInn1262F2uUY+I+raszZeR+c2OAi/lVsF+tR0l6Ap2TrnhQHvOPGefikLuk+nd8NDr8fIIqzk9cQpukbiSMezvwhBim4Qe2XEwGHeXMV5TdYaksXHwGWCD0cS2NSBFHs6YrgE/V/VgBSYiCNfQCFF0HeNikq/BXd52d+xb54As8XBzzKJBZgmiQ93pKqkSmCtIVS+py8YPmh5wLW0+cS7pfMhsTEDv5AZBJcMKaqhdgzMG1NIyt1db4k1nkKUFUJYbMo9SCyrPptoU7Fc57tIaLweDzjSJOTR2kP4jqoZ8YprlkuDJgM2chrMJVmo+XzFqEBu6KfQnF0k9b0eVnj3dQlsea7Z1Fx+h5FXgDsBHuIlGLvPp/77QFMMz63J+1APBHKbeYK9IJfrHSsSWi/4nulNyoOfaGfrBkMeRzPOSshhEQcQUrCrkJbJxz24PVOQ+JVaioPfcmq5TeZ1j4="
        #signing key
        #GPG_KEY_NAME
        - secure: "ZzbdJVCZSsENUEN1BO/YKgLLJI+v0pOqzjwlZLlTYflTZZ6QAtSFhGOXSh9dJPqXx7wXvq8qUyDNC5cmjV66za+dIZQPvL01hAPGfWztLYSS35uz7UHtsVWrUFGCP/Z5LubJnooPUOW/tDldwUCJWJa4/Y2KFhL7DVBdXJRA4RHXbaFaZVIS8dhavHEtA4DRUwO1xKyPITmzU6t3ExSKShvkQvTiZZY3KR3uNaxICVvUfoDmuOvyu5BMM75aueIzN723bPti6Z0GJZYGfO6afNAJnXnJMHR+kAbwH+e/NbcFsdlaXv+3egSK2u+wgFQSYg/WZg4GZwweqMSeoq//CIbN74xsLOzFuJJeNKIiy1g9UorvqKzzN8T5pw/NhqrWsYzmyBxr9Kenxw61YcJJZrPNdypDaSn90v4l2Ma0pE7b9MlzUqisaarWP46upSe3R8MwwXgDCD1N5mpZRQv74DT7TiaiBxzzme8nKccIdPnka3kBq+fhu7LRkqVhkcc03S/0B0jrAO/EYqc7F5i0udGspX7DIIwKAy3bnK4bTcx3F37JIKDoM9RXZuBpCF1/UGH6yIf0coWCpJz05MgopWYLuAW9J0mF+YLpESd/Yo5mpt0BnXppUyR1k/uNZv3oiOwX5VOnocdVD+5kwrTxCWWmuJxNMBTTAbfoFxY3c9o="
        #GPG_PASSPHRASE
        - secure: "u7PraRPSYWMjBfzcVLwX5BksfwA1Dn5x4ctzi/K2yME+8CTVgwymJPv5oYZMynFIEKDoujwcePJysi73TF2BqnyTdeo4GYOzXF3rYdPNqhP6Fux0z14UqQ1X+p4Ic+jAFywboSJwrETMw7hjA6MGU1DRlBsZ2oU4qNpHYE1EUE4O7oftopNWpr1Tni6CUx4Pvk6YVPX1cKcc5SxObqH7GbLknDsQVfjCC2hgVl+rywmcUWScNzYTroxMBc2MUpYCxecN0I8aBOo8fluBgnqYcUpJweU0NrBgdZ5J40PnZP5m+C0o+heJt7EaXVtCQ6/pxuy1wYo/R9Idji0VPuw/H5gvyJwesOsKit2DDMqGQCePN4LRDaf6Mzb6+7TubPpzb+pEDQ2kzG8TNc6srd/G4rceETFXUcg54u45AuGF2TrlOSXV29upU4094MzizE4Jez2TFM55E+0rbpuP5hbf7LOd790zwClY5mcl1MAsyrzV18aT3slePy8TM+buXPY4Qv/OKapuyIYQ93OPxkAxnvftR/sszmS19QFO7MDXRNvMpENJl1a328WeVdycitNimdus1HLpo02haR4OXtsix+RlImG8DPHtNbp+GzzijpKgGiH0I/ThDHT79uM9RiZcN3e3irNe+BzNd2N+dsQnn9kGI3OGpuwck2I9spCBtSY="

addons:
  sonarcloud:
    organization: "albertoirurueta-github"
    token:
      secure: "TV9yKRoHHvRYUQmJJIKGP8vVMuSdxfgfSMBP++me3l2hmoHTKQrq9mzP7jULWD/QkuPfkzNZkZtJN48I6XmB+CypXIVc6QxEiOiSO5AlCPD0FuIMDYdZgF6ESjOhHrFOm07A3ktrbVnDIcw3bgDZUXCjUHZx3foQidQMSo2BRARMpDXByBUKOU6KM1Rf1STMrvhkcK3772mAdbMa0CecpIZanBktELL2eEKKcRzmOfsP+wjHSG3djQRxeS5Y48DgAW4E2yETaCjIa4LnoKtHNTebBi29h6u7WX9fVo05qKIQOAx9RMj/EHzqexrpLObRIGbcaz0sjIJ8VdrNquGp4K/a+pO6jaMMjKt2s/umOV/NjIUGMNI3vph5A8O72GO4YwGrwaUawwAWgWkU1Sk+nkBIRzPLmVjS8vNQKFpTxocaQ7doHWyceio8CLUVmkDVxqgH3noiE7vpzAsxXchkyrk17RmOk/8wwh8ZmE2f87q0ZlmF1tcW6amNxQmWUX0StUI4qVTgP9wJfKfjAZjTZelHbRuDKcTpz5u/HP2g2t9mwmrdwLKrGC+FAq2Dmm7Jd91+hViIIksr1eucuWeU1nGj2nt2Ztl1EKJGnVnb/J2nAVHbC5M4+Rc4ih9EIEjEOKiPAqzucqDgBBMZ6Bw/Cb2It8rPreYCXltd98osrwA="

#if timeout occurs, add travis_wait as in example below:
#script: travis_wait mvn clean jacoco:prepare-agent install jacoco:report site

#add: -Denvironment=test to activate CI profile to publish into gh-pages
script:
  - travis_wait mvn clean jacoco:prepare-agent install jacoco:report -P !build-extras
  - mvn site -Djacoco.skip -DskipTests -P !build-extras
  - sonar-scanner

cache:
  directories:
  - ~/.m2/repository

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH_TOKEN
  keep-history: true
  local-dir: ./target/site
  on:
    branch: develop

after_success:
- ./cd/before-deploy.sh
- ./cd/deploy.sh
