name: Publish package to the Maven Central repository
on:
  release:
    # We'll run this workflow when a new Github release is created
    types: [created]
jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
        server-id: ossrh-release
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}